"""events

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-11 11:18:18.965842
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("area_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("uid", sa.String(length=255), nullable=False),
        sa.Column("series_id", sa.Uuid(), nullable=True),
        sa.Column("recurrence_id", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("tzid", sa.String(length=64), nullable=False),
        sa.Column("rrule", sa.String(length=300), nullable=True),
        sa.Column("exdates", postgresql.ARRAY(sa.DateTime(timezone=True)), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("transparency", sa.String(length=12), nullable=False),
        sa.Column("is_fixed", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("attendees", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reminders", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, '') || ' ' || coalesce(location, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('tentative', 'confirmed', 'cancelled')", name=op.f("ck_events_status")
        ),
        sa.CheckConstraint(
            "transparency in ('opaque', 'transparent')", name=op.f("ck_events_transparency")
        ),
        sa.CheckConstraint(
            "(series_id is null) = (recurrence_id is null)", name=op.f("ck_events_override_pair")
        ),
        sa.CheckConstraint("end_at >= start_at", name=op.f("ck_events_end_after_start")),
        sa.ForeignKeyConstraint(
            ["area_id"], ["areas.id"], name=op.f("fk_events_area_id_areas"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_events_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["events.id"],
            name=op.f("fk_events_series_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint(
            "uid",
            "recurrence_id",
            name="uq_events_uid_recurrence",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index("ix_events_area_start", "events", ["area_id", "start_at"], unique=False)
    op.create_index(
        "ix_events_search", "events", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_events_series", "events", ["series_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_series", table_name="events")
    op.drop_index("ix_events_search", table_name="events", postgresql_using="gin")
    op.drop_index("ix_events_area_start", table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
